### ISSUE TITLE
trouble building

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#51]
<a href="https://github.com/jeremysimmons"><img src="https://avatars0.githubusercontent.com/u/1406886?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jeremysimmons](https://github.com/jeremysimmons)**
_Friday Nov 06, 2015 at 03:03 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/260_

----

cannot build with rake script after downloading v1.9.71.2
Microsoft Windows [Version 6.3.9600]
ruby 2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]

rake aborted!
NoMethodError: undefined method `msbuild' for main:Object
C:/Users/simmonsj/Downloads/commandline-1.9.71.2/commandline-1.9.71.2/Rakefile.rb:51:in`<top (required)>'
C:/Ruby22/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
C:/Ruby22/lib/ruby/2.2.0/rake/rake_module.rb:28:in`load_rakefile'
C:/Ruby22/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
C:/Ruby22/lib/ruby/2.2.0/rake/application.rb:94:in`block in load_rakefile'
C:/Ruby22/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
C:/Ruby22/lib/ruby/2.2.0/rake/application.rb:93:in`load_rakefile'
C:/Ruby22/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
C:/Ruby22/lib/ruby/2.2.0/rake/application.rb:176:in`standard_exception_handling'
C:/Ruby22/lib/ruby/2.2.0/rake/application.rb:75:in `run'
C:/Ruby22/bin/rake:33:in`<main>'

**Comment by ericnewton76** [comment]
<a href="https://github.com/jeremysimmons"><img src="https://avatars0.githubusercontent.com/u/1406886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeremysimmons](https://github.com/jeremysimmons)**
_Friday Nov 06, 2015 at 03:07 GMT_

----

is this an issue with me having a newer version of albacore?

https://github.com/Albacore/albacore/wiki/build

> gem list
> albacore (2.5.4)
> ast (2.1.0)
> astrolabe (1.3.1)
> bigdecimal (1.2.6)
> io-console (0.4.3)
> json (1.8.1)
> map (6.5.5)
> mini_portile (0.6.2)
> minitest (5.4.3)
> nokogiri (1.6.6.2 x86-mingw32)
> parser (2.2.3.0)
> power_assert (0.2.2)
> powerpack (0.1.1)
> psych (2.0.8)
> rainbow (2.0.0)
> rake (10.4.2)
> rdoc (4.2.0)
> rubocop (0.34.2)
> ruby-progressbar (1.7.5)
> semver2 (3.4.2)
> test-unit (3.0.8)
